name: 百聆（bailing） 
version: 1.0

logging:
  level: debug

# 唤醒词
WakeWord: 相一

interrupt: false
# 是否开启工具调用
StartTaskMode: true
# 具体处理时选择的模块
selected_module:
  Recorder: RecorderPyAudio
  ASR: FunASR
  VAD: SileroVAD
  LLM: OpenAILLM
  TTS: EdgeTTS
  # TTS: MacTTS
  # TTS: CHATTTS
  Player: PygameSoundPlayer

Recorder:
  RecorderPyAudio:
    output_file: tmp/

ASR:
  FunASR:
    #model_dir: models/SenseVoiceSmall
    model_dir: FunAudioLLM/SenseVoiceSmall
    output_file: tmp/

VAD:
  SileroVAD:
    sampling_rate: 16000
    threshold: 0.5
    min_silence_duration_ms: 200  # 如果说话停顿比较长，可以把这个值设置大一些

LLM:
  OpenAILLM:
    model_name: deepseek-chat
    url: https://api.deepseek.com
    api_key: sk-xx

TTS:
  MacTTS:
    voice: Tingting
    output_file: tmp/
  EdgeTTS:
    voice: zh-CN-XiaoxiaoNeural
    output_file: tmp/
  GTTS:
    lang: zh
    output_file: tmp/
  CosyvoiceTTS:
    model_dir: FunAudioLLM/CosyVoice-300M-SFT
    output_file: tmp/
  CHATTTS:
    model_dir: 2Noise/ChatTTS
    output_file: tmp/

Player:
  PygameSoundPlayer: null
  PygamePlayer: null
  CmdPlayer: null
  PyaudioPlayer: null

Rag:
  doc_path: documents/
  # emb_model: models/bge-small-zh
  emb_model: BAAI/bge-small-zh-v1.5
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-xx

Memory:
  dialogue_history_path: tmp/
  memory_file: tmp/memory.json
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-xx

TaskManager:
  functions_call_name: plugins/function_calls_config.json





